#@TYPE: Machine
#@NAME: Yaqoud Orin Nano (based on Jetson Orin Nano devkit)
#@DESCRIPTION: Yaqoud IVI platform on Jetson Orin Nano 8GB

# Pull in everything from the upstream devkit
require conf/machine/jetson-orin-nano-devkit.conf

# Override rootfs partition to use most of the 128GB eMMC
# 100GB in bytes
# ROOTFSPART_SIZE_DEFAULT = "107374182400"