# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-yaqoud-ivi"
BBFILE_PATTERN_meta-yaqoud-ivi = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-yaqoud-ivi = "10"

LAYERDEPENDS_meta-yaqoud-ivi = "core flutter-layer virtualization-layer"

LAYERSERIES_COMPAT_meta-yaqoud-ivi = "scarthgap"
BBPATH .= ":${LAYERDIR}/conf"

